[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
tracing = "0.1.35"

[dependencies.clap]
version = "3.2.8"
features = ["derive"]

[dependencies.driver]
path = "../driver"

[dependencies.tracing-subscriber]
version = "0.3.14"
features = ["fmt"]
